### ISSUE TITLE
Type is invalid error when importing

### ISSUE THREAD

**Issue by seenickcode** [FormidableLabs/prism-react-renderer#146]
Hello, I'm following the example in the README but am getting an error that I can't seem to solve:

```
import React from "react";
import Highlight from "prism-react-renderer";

export default function CodeBlock(props) {
  return <Highlight>foobar</Highlight>;
}
```

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at ReactDOMServerRenderer.render (/pathtomyproject/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:4053:17)
    at ReactDOMServerRenderer.read (/pathtomyproject/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (/pathtomyproject/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at Object.renderToStaticMarkup (@astrojs/renderer-react/server.js:64:40)
    at Module.renderComponent (/node_modules/.pnpm/astro@0.21.13/node_modules/astro/dist/runtime/server/index.js?v=97d97296:199:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by matteobucci** [comment]
Hello, have you found a solution?
