### ISSUE TITLE
Unknown plugin "@babel/plugin-proposal-class-properties"

### ISSUE THREAD

**Issue by sourabhv** [FormidableLabs/prism-react-renderer#17]
Hey, I am using your library with a react-native app with 

```
"babel-cli": "6.24.0",
"react": "16.0.0",
"react-native": "^0.50.4",
```

And I get this error:

    ReferenceError: Unknown plugin "@babel/plugin-proposal-class-properties" specified in "/home/circleci/rnapp/node_modules/prism-react-renderer/package.json" at 0, attempted to resolve relative to "/home/circleci/rnapp/node_modules/prism-react-renderer"
      
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
          at Array.map (<anonymous>)
      at Function.normalisePlugins (node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
      at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (node_modules/babel-core/lib/transformation/file/index.js:135:24)
      at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:16)

I also tried this this by updating `babel-cli` to `7.0.0` but I get the same error

**Comment by kitten** [comment]
Oh, that's really odd! I wasn't aware that Metro Bundler now picks up all custom babel configs for modules. Is your setup as usual? As in, the package is simply installed with npm/yarn?

If so, I'll prepare another release that splits out the babel config into a babelrc and excludes it from the published package.

**Comment by sourabhv** [comment]
Yes, I used npm to install the package
